# import require packages

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# import data set 
loan_df = pd.read_csv('train.csv')

In [3]:
#drop unnessery columns 
def removeUnrequireColumns(df):
    df = df.drop(['Loan_ID','Married','Dependents','Self_Employed','ApplicantIncome',
              'CoapplicantIncome','Loan_Amount_Term'],axis=1)
    return df
new_loan_df = removeUnrequireColumns(loan_df)

In [4]:
new_loan_df.head()

Gender     Education  LoanAmount  Credit_History Property_Area Loan_Status
0   Male      Graduate         NaN             1.0         Urban           Y
1   Male      Graduate       128.0             1.0         Rural           N
2   Male      Graduate        66.0             1.0         Urban           Y
3   Male  Not Graduate       120.0             1.0         Urban           Y
4   Male      Graduate       141.0             1.0         Urban           Y

In [5]:
# check the null fields on new data set
new_loan_df.isnull().sum()

Gender            13
Education          0
LoanAmount        22
Credit_History    50
Property_Area      0
Loan_Status        0
dtype: int64

In [6]:
# remove all Null Val
def replaceAllNullField(df):
    df.Gender= df['Gender'].fillna('Male')
    df.LoanAmount= df.LoanAmount.fillna(df.LoanAmount.mean())
    df.Credit_History= df.Credit_History.fillna(round(df.Credit_History.mean()))

In [7]:
replaceAllNullField(new_loan_df)

In [8]:
new_loan_df.isnull().sum()

Gender            0
Education         0
LoanAmount        0
Credit_History    0
Property_Area     0
Loan_Status       0
dtype: int64

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [10]:
# convert string values into number
def stringToNumberConverter(df,noOfColumns):
    for i in range(0, noOfColumns):
        df[:,i] = le.fit_transform(df[:,i])

In [11]:
from sklearn.model_selection import train_test_split
y= new_loan_df.iloc[:,5].values
x= new_loan_df.iloc[:,:5].values
X_train, X_test, y_train, y_test = train_test_split( x, y, test_size=0.33, random_state=22)

In [12]:
y_train = le.fit_transform(y_train)
y_test = le.fit_transform(y_test)
stringToNumberConverter(X_train,5)
stringToNumberConverter(X_test,5)

# Applying KNN 

In [13]:
from sklearn.neighbors import KNeighborsClassifier

In [14]:
knc = KNeighborsClassifier(n_neighbors=2)

In [15]:
knc.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=2, p=2,
           weights='uniform')

In [16]:
y_predict=knc.predict(X_test)

In [17]:
# accuracy check 
from sklearn.metrics import accuracy_score

In [18]:
accuracy_score(y_predict,y_test)

0.6403940886699507

In [19]:
from random import randint

In [33]:
def showfinalAccurateResult(l):
    global X_test,y_test
#     X_test = np.append(X_test,np.array([l]),axis=0)
#     y_test = np.append(y_test,np.array(randint(0,1)))
#     print(len(x_test))
    
    return knc.predict([l])

In [34]:
# def get_max_position():
#     store_score = []
#     y= new_loan_df.iloc[:,5].values
#     x= new_loan_df.iloc[:,:5].values
#     for i in range(1,100):
#         X_train, X_test, y_train, y_test = train_test_split( x, y, test_size=0.33, random_state=22)
#         stringToNumberConverter(X_train,5)
#         stringToNumberConverter(X_test,5)
#         knc = KNeighborsClassifier(n_neighbors=i)
#         knc.fit(X_train,y_train)
#         y_pred = knc.predict(X_test)
#         store_score.append(accuracy_score(y_pred,y_test))
#     print(store_score.index(max(store_score)))

# get_max_position()

In [35]:
# showfinalAccurateResult([1  , 1, 267,   5,   0])

array([1])

In [38]:
X_train

array([[1, 0, 27, 1, 2],
       [1, 0, 97, 1, 0],
       [1, 1, 45, 1, 1],
       ...,
       [1, 1, 45, 0, 2],
       [1, 0, 102, 1, 0],
       [1, 0, 23, 1, 1]], dtype=object)

In [39]:
y_train

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,